version: "3.8"
services:
  db:
    image: postgres:16
    container_name: healthapp-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: healthapp
      POSTGRES_USER: health
      POSTGRES_PASSWORD: health
    volumes:
      - healthapp_data:/var/lib/postgresql/data
volumes:
  healthapp_data:
